### ISSUE TITLE
About the Left censoring method

### ISSUE THREAD

**Issue by rtrepos** [poypoyan/edhsmm#15]
Hello,
First I would like to thank you for the code you provided on hsmm that works very fine.
I am very interested to apply left censoring on my dataset and as far as I know, your software is the only one to have this option.
You mentioned in your notebook that it is an experimental feature, could you, please, give me more information ? (references, ...)
Thanks in advance 
Ronan

**Comment by poypoyan** [comment]
Hello,

This is just an acknowledgement for now. I will get into this a bit later, because I am not doing machine learning these days.

I will just say two things:
* I am not even sure that "left-censoring" is the correct term for that.
* My reference for both left and right censoring is section 2.2.1. of Yu. The "general assumption" there is when both left and right censoring are ON in my edhsmm.
![Yu Section 2.2.1](https://user-images.githubusercontent.com/64708703/222010429-370f5e75-d8cd-4184-a77c-73ac3bc69403.png)
However, Yu describes a very general hsmm there, so there is a need to simplify the formulas for (explicit duration) hsmm. I need to check again how I implemented left censoring in my code. Then I will add details in my code (esp. _hsmm_core.pyx) and the notebook. 

I recommend against using left_censor for serious purposes for now.

Thanks for the feedback!

**Comment by rtrepos** [comment]
Thank you for your quick answer. It looks promising and deserves to be tested indeed.
